ignore:
  - "autohbw/.*"
  - "examples/autohbw*"
  - "examples/*example*"
  - "examples/memkind*"
  - "src/tbb_wrapper.c"
  - "test/.*"
  - "utils/**/*"

coverage:
  range: "60...100"
  status:
    project: off
    patch:
      default:
        informational: true
    changes: off

comment:
  layout: "diff"
  behaviour: default
  require_changes: true
